### ISSUE TITLE
How to parse commands?

### ISSUE THREAD

**Issue by bralbral** [ARKhoshghalb/django-tgbot_demo#1]
Good day!

Is there a command parser decorator?

**Comment by bralbral** [comment]
UPDATE: 

1. You need set command in bot.py file:

```
bot.setMyCommands([BotCommand({
        'command': "test",
        'description': "test"
    })])
```
2. Send /test to bot 
3.  You can see it in Update -> Obj -> Message ->entitites
![image](https://user-images.githubusercontent.com/54455457/117568924-bbc48400-b0cb-11eb-9e78-8eb173714ff6.png)

**Comment by Ali-Toosi** [comment]
Hi,
Sorry I somehow missed the notification of your first message here.
There aren't any special parsers/functions for commands but you can either read them as plain text or as other types that Telegram supports (e.g. the way you have found).
Also thanks a lot for adding your finding here, it would be helpful for others.
I'm closing this but feel free to reopen if there are other things to add.
