### ISSUE TITLE
No notification style messaging

### ISSUE THREAD

**Issue by Schroedingberg** [ARKhoshghalb/django-tgbot_demo#2]
It seems like the bots created with this app are unable to send messages without prior user interaction (i.e. a subscriber to the bot sends a message in telegram). I suppose this should theoretically be possible since the bot API allows this. I haven't been able to figure this out so far. Is this a bug or am I missing something?

**Comment by Ali-Toosi** [comment]
Hi,
This is a limitation of the Bot API and Telegram does **not** allow this. I assume that is because otherwise bots could go around and spam users with unwanted messages. But anyway this is not something you could change from the code as it's something Telegram API is enforcing.

**Comment by Schroedingberg** [comment]
But shouldn't it work once I subscribed to the bot? There are plenty of telegram bots that e.g. send daily news updates and these are certainly sent without me sending a message every day.

**Comment by Ali-Toosi** [comment]
Oh I see your point now. Yes, this is _technically_ possible but you'd need to do some work for it. Meaning that there are no defined mechanisms right now that allow you to quickly send a message to everyone, you have to do it yourself. This is how I'd suggest you do it:
Create a processor that receives messages only from the admins (you can define who admins are). So whenever an admin sends a message that starts with !notify! the bot will send the rest of their message as a notification to everyone. This way, you are sending notifications with the same style of processing updates.
All of that said, this is probably a common use case and I'll probably add it as a feature to the package sometime in future.

**Comment by Schroedingberg** [comment]
Sounds great! If you need any help with that let me know, I will try my best :-)

**Comment by Ali-Toosi** [comment]
Would absolutely appreciate any contributions. If you have got ideas for implementing this (or possibly any other features) go for it!
As a matter of fact, an hour ago right after this discussion, I thought it's probably about time we added a contribution guide to the repo and added this to the list: https://github.com/Ali-Toosi/django-tgbot/blob/master/.github/CONTRIBUTING.md
